### ISSUE TITLE
App Not responding

### ISSUE THREAD

**Issue by anymv** [libDrive/heroku#1]
![image](https://user-images.githubusercontent.com/72621475/107487328-17a26e00-6bac-11eb-837d-13bd33aa29d2.png)
![image](https://user-images.githubusercontent.com/72621475/107487474-343ea600-6bac-11eb-8b0e-c0cf3064e897.png)

**Comment by eliasbenb** [comment]
I need the error logs.

**Comment by anymv** [comment]
![image](https://user-images.githubusercontent.com/72621475/107498583-fba5c900-6bb9-11eb-8f5d-56093ad78c1b.png)
Here

**Comment by eliasbenb** [comment]
> ![image](https://user-images.githubusercontent.com/72621475/107498583-fba5c900-6bb9-11eb-8f5d-56093ad78c1b.png)
> Here

I'm not sure what's going on, there are no logs at all, it even boots correctly.

Could you try opening the site in an incognito tab and maybe refresh the tab a couple of times.

**Comment by anymv** [comment]
> > ![image](https://user-images.githubusercontent.com/72621475/107498583-fba5c900-6bb9-11eb-8f5d-56093ad78c1b.png)
> > Here
> 
> I'm not sure what's going on, there are no logs at all, it even boots correctly.
> 
> Could you try opening the site in an incognito tab and maybe refresh the tab a couple of times.

I Redeployed it Two Times and Still 🥱

**Comment by eliasbenb** [comment]
> I Redeployed it Two Times and Still 🥱

There really isn't much I can do if there are no logs and no information on how to reproduce.

My best guess is you did something wrong in the config.
